// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjhfd9aIAE8gqJl3zPz55hsc05oaq1xEA',
    appId: '1:239569121289:web:6cec5b1623d5396361c8d8',
    messagingSenderId: '239569121289',
    projectId: 'mobileapp-ff685',
    authDomain: 'mobileapp-ff685.firebaseapp.com',
    storageBucket: 'mobileapp-ff685.firebasestorage.app',
    measurementId: 'G-QSFD1QGZP6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8Ihz34Vp520IbP6NzFF0fDNTsEDgGY3Q',
    appId: '1:239569121289:android:c557ef0fe494534f61c8d8',
    messagingSenderId: '239569121289',
    projectId: 'mobileapp-ff685',
    storageBucket: 'mobileapp-ff685.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6yMMzjEZrGiiMpt9F4FUTJN8_QbcpjRs',
    appId: '1:239569121289:ios:3f899ea56b236de261c8d8',
    messagingSenderId: '239569121289',
    projectId: 'mobileapp-ff685',
    storageBucket: 'mobileapp-ff685.firebasestorage.app',
    iosBundleId: 'com.pcpstudent.seasonSirMobileapp',
  );
}
